apiVersion: v1
kind: Pod
metadata:
  name: charon
  labels:
    app: charon
spec:
  containers:
  - name: charon
    image: pangealab/charon:latest
    volumeMounts:
    - name: kali-root
      mountPath: /root
    # - name: kali-postgres
    #   mountPath: /var/lib/postgresql/14/main
  # initContainers:
  # - name: change-ownership-container
  #   image: busybox
  #   command: ["/bin/chown","-R","117:125","/var/lib/postgresql/14/main"]
  #   securityContext:
  #     runAsUser: 0
  #     privileged: true
  #   volumeMounts:
  #   - name: kali-postgres
  #     mountPath: /var/lib/postgresql/14/main
  volumes:
  - name: kali-root
    persistentVolumeClaim:
      claimName: kali-root
  # - name: kali-postgres
  #   persistentVolumeClaim:
  #     claimName: kali-postgres
---      
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: kali-root
  labels:
    app: charon  
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
# ---
# kind: PersistentVolumeClaim
# apiVersion: v1
# metadata:
#   name: kali-postgres
#   labels:
#     app: charon  
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 10Gi  
