# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: charon
#   labels:
#     app: charon
# spec:
#   type: LoadBalancer
#   ports:
#   - port: 389
#     targetPort: 389
#   selector:
#     app: castor       
---
apiVersion: v1
kind: Pod
metadata:
  name: charon
  labels:
    app: charon
spec:
  containers:
  - name: charon
    image: pangealab/charon:latest
    ports:
    # - containerPort: 389
    env:
    # - name: KEY
    #   value: VALUE
    volumeMounts:
    - name: kali-root
      mountPath: /root
    - name: kali-postgres
      mountPath: /var/lib/postgresql/data
  volumes:
  - name: kali-root
    persistentVolumeClaim:
      claimName: kali-root
  - name: kali-postgres
    persistentVolumeClaim:
      claimName: kali-postgres
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: kali-root
  labels:
    app: charon  
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: kali-postgres
  labels:
    app: charon  
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi